### ISSUE TITLE
Z-Push 2.7.3 has been released

### ISSUE THREAD

**Issue by marclaporte** [si458/zpush#3]
https://z-push.org/z-push-2-7-3-released/

As of now, 2.7.2 is available here: https://github.com/si458/zpush/pkgs/container/zpush

**Comment by si458** [comment]
all done :) 
https://github.com/si458/zpush/actions/runs/9959479924/job/27516414785
https://github.com/si458/zpush/releases/tag/v2.7.3
https://github.com/users/si458/packages/container/zpush/244412403?tag=v2.7.3
